name = "gamelootx-ui"
pages_build_output_dir = "."
compatibility_date = "2025-08-14"

[functions]
directory = "functions"

# Optional: If you want to log or test environment variables
# [vars]
# SUPABASE_URL = "https://fzduhyreyrwczebvtsmg.supabase.co"
# SUPABASE_ANON_KEY = "your-non-sensitive-key"
