name = "gamelootx-ui"
compatibility_date = "2025-08-12"

[site]
bucket = "."
entry-point = "functions"

[env.production]
vars = { 
  BOT_TOKEN = "8451731848:AAH9QzDbCdUq5PoQtmwyLucmSlkMpSjEBJM",
  ADMIN_ID = "5778437193",
  NOWPAYMENTS_API_KEY = "C3W1DDF-C4GMSZC-HQPJC7M-MJWWSNQ",
  SUPABASE_URL = "https://fzduhyreyrwczebvtsmg.supabase.co",
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
}
