name = "gamelootx-ui"
pages_build_output_dir = "."
compatibility_date = "2025-08-14"

[functions]
directory = "functions"

[vars]
SUPABASE_URL = "https://fzduhyreyrwczebvtsmg.supabase.co"
SUPABASE_ANON_KEY = "your-non-sensitive-key"
